### ISSUE TITLE
compilation of system fails on markup.lisp line 216

### ISSUE THREAD

**Issue by ghost** [gigamonkey/monkeylib-markup#1]
Fails on:

(#\§ (open-paragraph parser "section")
           (process-token parser token))

via Quicklisp load:

(ql:quickload 'com.gigamonkeys.markup)

The error in in Slime (under CCL - happens in Lispworks and SBCL too) is:

Unknown character name - "Â§" .
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY-COMPILE-FILE] Retry compiling #P"/Users/lriley/src/monkeylib-markup/markup.lisp"
 1: [SKIP-COMPILE-FILE] Skip compiling #P"/Users/lriley/src/monkeylib-markup/markup.lisp"
 2: [RETRY] Retry compiling #<CL-SOURCE-FILE "com.gigamonkeys.markup" "markup">.
 3: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "com.gigamonkeys.markup" "markup"> as having been successful.
 4: [ABORT] Give up on "com.gigamonkeys.markup"
 5: [RETRY] Retry SLIME REPL evaluation request.
 --more--

Backtrace:
  0: (#<Anonymous Function #x3000004DAA3F> #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> #\ NIL)
  1: (CCL::READ-DISPATCH #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> ##)
  2: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> ## (NIL))
  3: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> (NIL) #))
  4: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> NIL #))
  5: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> #( (NIL))
  6: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> (NIL) #))
  7: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> NIL #))
  8: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> #( (NIL))
  9: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> (NIL) #))
 10: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> NIL #))
 11: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> #( (NIL))
 12: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> (NIL) #))
 13: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> NIL #))
 14: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> #( NIL)
 15: (CCL::%READ-FORM #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> NIL (NIL))
 16: (CCL::READ-INTERNAL #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> NIL (NIL) NIL)
 17: (CCL::READ-RECORDING-SOURCE #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/lriley/src/monkeylib-markup/markup.lisp"/7 ISO-8859-1) #x3020010F354D> :EOFVAL (NIL) :FILE-NAME "home:src;monkeylib-markup;mark..

Environment:

OSX Lion. Cocoa Emacs. Slime. UTF-8 for Emacs and UTF-8 for Slime.

**Comment by gigamonkey** [comment]
This is presumably because the source is not being parsed as UTF-8. You can change your locale so that UTF-8 is the default (what I do) or you can possibly tell your Lisp somehow that UTF-8 is the default. I don't know of anything I can do in the code to fix this.

**Comment by ghost** [comment]
I figured it out. Though Emacs and Slime configs were specifying UTF-8, Clozure CL was not using UTF-8. I did:

(setf ccl:_default-file-character-encoding_ :utf-8)

and then loaded again in Quicklisp and all was well.

Even better was to add (setenv "LANG" "en_US.UTF-8") to my .emacs file.
